version: '3'

services:
  jwt-create:
    build:
      context: ./jwt-create
    networks:
      - app-network

  jwt-verify:
    build:
      context: ./jwt-verify
    networks:
      - app-network

  front-public:
    build:
      context: ./front-public
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
